-- AlterEnum
ALTER TYPE "ActionRequestType" ADD VALUE 'DATA_ACCESS_REQUEST';
ALTER TYPE "ActionRequestType" ADD VALUE 'DATA_ERASURE_REQUEST';
ALTER TYPE "ActionRequestType" ADD VALUE 'DATA_CORRECTION_REQUEST';
