import { Router } from 'express';
import { authRouter } from '@/modules/auth/auth.controller';
import { mfaRouter } from '@/modules/auth/mfa.controller';
import { usersRouter } from '@/modules/users/users.controller';
import { coursesRouter } from '@/modules/courses/courses.controller';
import { facultyRouter } from '@/modules/faculty/faculty.controller';
import { parentsRouter } from '@/modules/parents/parents.controller';
import { studentsRouter } from '@/modules/students/students.controller';
import { batchesRouter } from '@/modules/batches/batches.controller';
import { batchTransfersRouter } from '@/modules/batchTransfers/batchTransfers.controller';
import { sessionsRouter } from '@/modules/sessions/sessions.controller';
import { attendanceRouter } from '@/modules/attendance/attendance.controller';
import { tasksRouter } from '@/modules/tasks/tasks.controller';
import { notificationsRouter } from '@/modules/notifications/notifications.controller';
import { questionsRouter } from '@/modules/questions/questions.controller';
import { examsRouter } from '@/modules/exams/exams.controller';
import { gradesRouter } from '@/modules/grades/grades.controller';
import { behaviourRouter } from '@/modules/behaviour/behaviour.controller';
import { presentationsRouter } from '@/modules/presentations/presentations.controller';
import { studentOfMonthRouter } from '@/modules/studentOfMonth/studentOfMonth.controller';
import { interventionsRouter } from '@/modules/interventions/interventions.controller';
import { selfAssessmentsRouter } from '@/modules/selfAssessments/selfAssessments.controller';
import { certificationsRouter } from '@/modules/certifications/certifications.controller';
import { certificatesRouter } from '@/modules/certificates/certificates.controller';
import { publicVerifyRouter } from '@/modules/certificates/verify.controller';
import { dashboardRouter } from '@/modules/dashboard/dashboard.controller';
import { settingsRouter } from '@/modules/settings/settings.controller';
import { auditLogsRouter } from '@/modules/auditLogs/auditLogs.controller';
import { reportsRouter } from '@/modules/reports/reports.controller';
import { feesRouter } from '@/modules/fees/fees.controller';
import { publicVerifyReceiptRouter } from '@/modules/fees/verifyReceipt.controller';
import { projectsRouter } from '@/modules/projects/projects.controller';
import { internsRouter } from '@/modules/interns/interns.controller';
import { actionCentreRouter } from '@/modules/actionCentre/actionCentre.controller';
import { backupRouter } from '@/modules/backup/backup.controller';
import { consentRouter } from '@/modules/consent/consent.controller';
import { feedRouter } from '@/modules/feed/feed.controller';
import { calendarRouter } from '@/modules/calendar/calendar.controller';
import { searchRouter } from '@/modules/search/search.controller';
import { paperLibraryRouter } from '@/modules/exams/paperLibrary.controller';

export const apiRouter = Router();

apiRouter.use('/auth', authRouter);
apiRouter.use('/auth/mfa', mfaRouter);
apiRouter.use('/users', usersRouter);
apiRouter.use('/courses', coursesRouter);
apiRouter.use('/faculty', facultyRouter);
apiRouter.use('/parents', parentsRouter);
apiRouter.use('/students', studentsRouter);
apiRouter.use('/batches', batchesRouter);
apiRouter.use('/batch-transfers', batchTransfersRouter);
apiRouter.use('/sessions', sessionsRouter);
apiRouter.use('/attendance', attendanceRouter);
apiRouter.use('/tasks', tasksRouter);
apiRouter.use('/notifications', notificationsRouter);
apiRouter.use('/questions', questionsRouter);
apiRouter.use('/exams', examsRouter);
apiRouter.use('/paper-library', paperLibraryRouter);
apiRouter.use('/grades', gradesRouter);
apiRouter.use('/behaviour', behaviourRouter);
apiRouter.use('/presentations', presentationsRouter);
apiRouter.use('/student-of-month', studentOfMonthRouter);
apiRouter.use('/interventions', interventionsRouter);
apiRouter.use('/self-assessments', selfAssessmentsRouter);
apiRouter.use('/certifications', certificationsRouter);
apiRouter.use('/certificates', certificatesRouter);
apiRouter.use('/verify', publicVerifyRouter);
apiRouter.use('/dashboard', dashboardRouter);
apiRouter.use('/settings', settingsRouter);
apiRouter.use('/audit-logs', auditLogsRouter);
apiRouter.use('/reports', reportsRouter);
apiRouter.use('/fees', feesRouter);
apiRouter.use('/verify/receipt', publicVerifyReceiptRouter);
apiRouter.use('/projects', projectsRouter);
apiRouter.use('/interns', internsRouter);
apiRouter.use('/action-centre', actionCentreRouter);
apiRouter.use('/backup', backupRouter);
apiRouter.use('/consent', consentRouter);
apiRouter.use('/feed', feedRouter);
apiRouter.use('/calendar', calendarRouter);
apiRouter.use('/search', searchRouter);
